essbeeapp/urls.py
from django.urls import path
from . import views

app_name = 'essbeeapp'

urlpatterns = [

    path('', views.index, name='index'),
    path('contact', views.ContactView, name='contact'),
    path('about', views.about, name='about'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('contactUs', views.contactUs, name='contactUs'),
    path('news', views.news, name='news'),
    path('chat', views.chat, name='chat'),
    path('clients', views.clients, name='clients'),
    path('blog', views.blog, name='blog'),
    path('<slug:c_slug>/', views.service, name='service'),
    path('news/<slug:n_slug>/', views.latestNews, name='latestNews'),
    path('mission', views.mission, name='mission'),





]


sbinfo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('essbeeapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Blog(models.Model):
    heading=models.CharField(max_length=200)
    desc=models.TextField(blank=True)
    img=models.ImageField(upload_to='blog')
    author=models.CharField(max_length=100,default=None)
    date=models.DateField()
    list_display = ('heading', 'author', 'date')

    class Meta:
        verbose_name_plural = "Blogs"
        ordering = ('-date',)


    def __str__(self):
        return self.heading

contact/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name=models.CharField(max_length=100,blank=False,null=False)
    from_email = models.EmailField()
    mobile_num=models.IntegerField(default=None)
    message = models.TextField()
    date=models.DateTimeField(auto_now=True)


    class Meta:
      verbose_name_plural = "Contacts"



    def __str__(self):
       return self.name + "-" + self.from_email

latestNews/models.py

from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
from django.urls import reverse


class LatestNews(models.Model):
    img=models.ImageField(upload_to='news')
    heading=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(max_length=255,unique=True)
    sub_heading=models.CharField(max_length=255)
    desc=models.TextField()

    class Meta:
        ordering = ("heading",)
        verbose_name = 'LatestNews'
        verbose_name_plural = 'LatestNews'

    def __str__(self):
        return self.heading

    def save(self, *args, **kwargs):
        self.slug = slugify(self.heading)
        return super(LatestNews, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("essbeeapp:latestNews",kwargs={'n_slug':self.slug})

service/models.py
from django.db import models

from django.template.defaultfilters import slugify

# Create your models here.
from django.urls import reverse


class Service(models.Model):
    img_icon = models.ImageField(upload_to='service',null=True)
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    desc = models.CharField(max_length=200)
    img = models.ImageField(upload_to='service_img')

    class Meta:
        ordering = ("name",)
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Service, self).save(*args, **kwargs)

    def get_detail_url(self):
        return reverse("essbeeapp:service",kwargs={'c_slug':self.slug})

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

latestNews/views.py
from django.shortcuts import render

# Create your views here.

service/views.py
from django.shortcuts import render

# Create your views here.

templates/include/LatestNews.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}LATEST NEWS{% endblock %}
{% block content %}
<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="{% static 'css/service/service.css' %}">
</head>

<body>
    <div class="article-clean">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
                    <div class="intro">
                        <h1 class="text-center">{{news.heading}}</h1>
                        <p class="text-center"><img class="img-fluid" src="{{news.img.url}}"></p></div>
                    <div class="text">
                        <p>{{news.desc}}.</p>
<!--                        <figure><img class="figure-img" src="{{results.img.url}}">-->
<!--                            <figcaption>Caption</figcaption>-->
<!--                        </figure>-->
                        <p>{{news.sub_heading}}.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

</body>

{% endblock %}


templates/include/about.html
{% extends 'base1.html' %}
{% block title %}ABOUT US {% endblock %}
{% load static %}
{% block content %}
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}


*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}

.container {
  padding: 0 16px;
  background-color:#D8D8D8;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
</style>
</head>
<body>

<div class="about-section">
  <h1>About Us </h1>
  <p>Helping Clients Create the Future</p>
  <p>Essbee Techstrategies combines tech expertise and business intelligence to catalyze change and deliver results.</p>
  <p>Essbee Techstrategies Private Limited is a Private incorporated on 18 March 2021. It is classified as Non-govt company and is registered at Registrar of Companies, Ernakulam.</p>
  <p>It is inolved in Other computer related activities [for example maintenance of websites of other firms/ creation of multimedia presentations for other firms etc.]
  </p>
</div>

<h2 style="text-align:center; padding-top:20px;" >Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="{% static 'images/person.jpg' %}" alt="profile" style="width:100%">
      <div class="container">
        <br>
        <h3>MUHAMMED SHIBILY</h3>
        <p class="title">CEO & Founder</p>
        <p>Muhammed Shibily is registered with Ministry of Corporate Affairs (MCA). Their DIN is 09112539. Following is their current and past directorship holdings.</p>
        <p>info@essbeeinfotech.com</p>

      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="{% static 'images/person.jpg' %}" alt="profile" style="width:100%">
      <div class="container">
        <br>
        <h3>ASHMI JAMAL</h3>
        <p class="title"> Director</p>
        <p>Ashmi Jamal is registered with Ministry of Corporate Affairs (MCA). Their DIN is 09112540. Following is their current and past directorship holdings.</p>
        <p>info@essbeeinfotech.com</p>

      </div>
    </div>
  </div>
  
<!--  <div class="column">-->
<!--    <div class="card">-->
<!--      <img src="{% static 'images/person1.jpg' %}" alt="John" style="width:100%">-->
<!--      <div class="container">-->
<!--        <h2>John Doe</h2>-->
<!--        <p class="title">Designer</p>-->
<!--        <p>Some text that describes me lorem ipsum ipsum lorem.</p>-->
<!--        <p>john@example.com</p>-->
<!--        <p><button class="button">Contact</button></p>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
</div>
{% endblock %}

templates/include/blog.html
{% extends 'base1.html' %}
{% block title %}OUR BLOG {% endblock %}
{% load static %}
{% block content %}
<link href="{% static 'css/blog/blog.css' %}" rel="stylesheet">
<div class="blog-home3 py-5">
  <div class="container">
    <!-- Row  -->
    <div class="row justify-content-center">
      <!-- Column -->
      <div class="col-md-8 text-center">
        <h3 class="my-3">Latest News and Blog from WrapKit</h3>
        <h6 class="subtitle font-weight-normal">You can relay on our amazing features list and also our customer services will be great experience for you without doubt</h6>
      </div>
      <!-- Column -->
      <!-- Column -->
    </div>
    <div class="row mt-4">
      <!-- Column -->
       {% for blogs in blogs %}
      <div class="col-lg-6">
        <div class="card border-0 mb-4">
          <img class="card-img-top" src="{{blogs.img.url}}">
          <div class="date-pos text-center text-white p-3 bg-success-gradiant">{{blogs.author}} &nbsp; &nbsp; {{blogs.date}}</div>
          <h5 class="font-weight-medium mt-3"><a href="#" class="link text-decoration-none">{{blogs.heading}}</a></h5>
          <p class="m-t-20">{{blogs.desc}} </p>
        </div>
      </div>
       {% endfor %}
      <!-- Column -->
      <div class="col-lg-6">
        <div class="row">
          <!-- Column -->
          {% for blogs in blog %}
          <div class="col-md-6">
            <div class="card border-0 mb-4">
              <img class="card-img-top" src="{{blogs.img.url}}" alt="wrappixel kit">
              <div class="date-pos text-center text-white p-3 bg-success-gradiant">{{blogs.author}} &nbsp; &nbsp; {{blogs.date}}</div>
              <h6 class="font-weight-medium mt-3"><a href="#" class="link text-decoration-none">{{blogs.desc}}</a></h6>
            </div>
          </div>
          {% endfor %}
          <!-- Column -->
<!--          <div class="col-md-6">-->
<!--            <div class="card border-0 mb-4">-->
<!--              <a href="#"><img class="card-img-top" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img6.jpg" alt="wrappixel kit"></a>-->
<!--              <div class="date-pos text-center text-white p-3 bg-success-gradiant">JOHN DOE &nbsp; &nbsp; SEPT 15, 2017</div>-->
<!--              <h6 class="font-weight-medium mt-3"><a href="#" class="link text-decoration-none">New Seminar on Newest Food Recipe</a></h6>-->
<!--            </div>-->
<!--          </div>-->
          <!-- Column -->
<!--          <div class="col-md-6">-->
<!--            <div class="card border-0 mb-4">-->
<!--              <a href="#"><img class="card-img-top" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img7.jpg" alt="wrappixel kit"></a>-->
<!--              <div class="date-pos text-center text-white p-3 bg-success-gradiant">JOHN DOE &nbsp; &nbsp; SEPT 15, 2017</div>-->
<!--              <h6 class="font-weight-medium mt-3"><a href="#" class="link text-decoration-none">New Seminar on Newest Food Recipe</a></h6>-->
<!--            </div>-->
<!--          </div>-->
          <!-- Column -->
<!--          <div class="col-md-6">-->
<!--            <div class="card border-0 mb-4">-->
<!--              <a href="#"><img class="card-img-top" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img8.jpg" alt="wrappixel kit"></a>-->
<!--              <div class="date-pos text-center text-white p-3 bg-success-gradiant">JOHN DOE &nbsp; &nbsp; SEPT 15, 2017</div>-->
<!--              <h6 class="font-weight-medium mt-3"><a href="#" class="link text-decoration-none">New Seminar on Newest Food Recipe</a></h6>-->
<!--            </div>-->
<!--          </div>-->
          <!-- Column -->
        </div>
      </div>
      <!-- Column -->
    </div>
  </div>
</div>
{% endblock %}

templates/include/clients.html
{% extends 'base1.html' %}
{% block title %}OUR CLIENTS {% endblock %}
{% block content %}
{% load static %}
<!-- our works -->
<section id="OurWork">
  <div class="container">
    <h2> Our Clients</h2>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
        <div class="grey-box">
          <img src="{% static 'images/sponser.png' %}" alt="Sponser">

        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-9">
        {% for works in work %}
        <div class="each-work space">
            <img src="{{works.img.url}}" alt="{{works.company_name}}">
        </div>
        {% endfor %}

      </div>
    </div>
  </div>
</section>

<!-- end of our works -->

{% endblock %}

templates/include/contact.html

<div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="post" ACTION="contact">
                {% csrf_token %}
                <h3>Drop Us a Message</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="name" required="required" class="form-control" placeholder="Your Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="from_email" class="form-control" required="required" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="mobile_num" class="form-control" required="required" placeholder="Your Phone Number *" value="" />
                        </div>
                        <script src='https://www.google.com/recaptcha/api.js'></script>
                        <div class="g-recaptcha" data-sitekey="6Lfnoc8aAAAAAEcLT3sKj1XmNnBgP7QhheXdeGWM"></div>
                         <br>

                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="message"  required="required" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>

                </div>




            </form>
    {% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

</div>

templates/include/contactUs.html
{% extends 'base1.html' %}
{% block title %}CONTACT US {% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/contactUS/contactus.css' %}">
<div class="contact3 py-5">
  <div class="row no-gutters">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="card-shadow">
            <img src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/contact/2.jpg" class="img-fluid">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="contact-box ml-3">
            <h1 class="font-weight-light mt-2">Quick Contact</h1>
            <form class="mt-4" method="POST" action="contact">
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-12">
                  <div class="form-group mt-2">
                    <input class="form-control" type="text" placeholder="name" name="name" required="required">
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="form-group mt-2">
                    <input class="form-control" type="email" placeholder="email address" name="from_email" required="required">
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="form-group mt-2">
                    <input class="form-control" type="text" placeholder="phone" name="mobile_num" required="required">
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="form-group mt-2">
                    <textarea class="form-control" rows="3" placeholder="message" name="message" required="required"></textarea>
                  </div>
                </div>
				  <!-- captcha -->
				  <script src='https://www.google.com/recaptcha/api.js'></script>
				  <div class="g-recaptcha" data-sitekey="6Lfnoc8aAAAAAEcLT3sKj1XmNnBgP7QhheXdeGWM"></div>
                  <!--  end of captcha -->
				  <div class="col-lg-12">
                  <button type="submit" class="btn btn-danger-gradiant mt-3 text-white border-0 px-3 py-2"><span> SUBMIT</span></button>
                </div>
              </div>
            </form>
            {% for message in messages %}
             <div class="container-fluid p-0">
              <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
               <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
               </button>
                {{ message }}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-12">
          <div class="card mt-4 border-0 mb-4">
            <div class="row">
              <div class="col-lg-4 col-md-4">
                <div class="card-body d-flex align-items-center c-detail pl-0">
                  <div class="mr-3 align-self-center">
                    <img src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/contact/icon1.png">
                  </div>
                  <div class="">
                    <h6 class="font-weight-medium">Address</h6>
                    <p class="">NO.55/1631,PARAKOTTU TOWERS
                      <br> ERNAKULAM,KERALA,INDIA-682020</p>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4">
                <div class="card-body d-flex align-items-center c-detail">
                  <div class="mr-3 align-self-center">
                    <img src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/contact/icon2.png">
                  </div>
                  <div class="">
                    <h6 class="font-weight-medium">Phone</h6>
                    <p class="">+91 9633334389
                      </p>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4">
                <div class="card-body d-flex align-items-center c-detail">
                  <div class="mr-3 align-self-center">
                    <img src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/contact/icon3.png">
                  </div>
                  <div class="">
                    <h6 class="font-weight-medium">Email</h6>
                    <p class="">
                      info@essbeeinfotech.com
                      <br> hrhotline@essbeeinfotech.com
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/include/footer.html
{% load static %}

<footer class="footer">
    <div class="row">
        <div class="col-sm-6 col-md-4 footer-navigation">
            <h4><a href="#">ESSBEE <span style="color:red">Techstrategies</span></a></h4>
            <p class="new-line-span">CIN : U72900KL2021PTC068116</p>
            <p class="links"><a href="{% url 'essbeeapp:index' %}">Home</a><strong> · </strong><a href="contactUs">Contact Us</a><strong> · </strong><a href="privacy_policy">Privacy Policy</a><strong> · </strong><a href="news">Latest News</a><strong> · </strong>
            <a href="about">About Us</a><strong> . </strong> <a href="chat">Live Chat</a><strong> . </strong><a href="mission">Mission </a>
            <p class="company-name">WWW.ESSBEEINFOTECH.COM © 2021</p>
        </div>
        <div class="col-sm-6 col-md-4 footer-contacts">
            <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                <p><span class="new-line-span">NO.55/1631,PARAKOTTU TOWERS</span> ERNAKULAM,KERALA,INDIA-682020</p>
            </div>
            <div><i class="fa fa-phone footer-contacts-icon"></i>
                <p class="footer-center-info email text-left"> +91 9633334389</p>
            </div>
            <div><i class="fa fa-envelope footer-contacts-icon"></i>
                <p> <a href="mailto:email@example.com" target="_blank">info@essbeeinfotech.com</a></p>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 footer-about">
            <h4>About the company</h4>
            <p>ESSBEE Infotech is one of the leading software company.</p>
            <div class="social-links social-icons">
                <a href="https://www.facebook.com/Essbee-Infotech-546155818802137"><i class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/EssbeeInfotech?s=09"><i class="fa fa-twitter"></i></a>
                <a href="https://wa.me/message/RHUSMHHFYLDKD1"><i class="fa fa-whatsapp"></i></a>
                <a href="https://www.instagram.com/essbeeinfotech"><i class="fa fa-instagram"></i></a>
                <a href="mailto:info@essbeeinfotech.com"><i class="fa fa-envelope-o"></i></a>
            </div>
        </div>
    </div>
</footer>

<div class="copyright">
    <div class="container">
        <div class="col-md-12 col-sm-12">
            <p>© 2021 - All Rights with <a href="https://www.essbeeinfotech.com">Essbee Infotech Pvt. Ltd.</a> | CIN : U72900KL2021PTC068116</p>
        </div>
    </div>
</div>

templates/include/live_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />

        <title>Live Chat</title>
        <meta name="description" content="Tuts+ Chat Application" />
        <link rel="stylesheet" href="{% static 'css/liveChat/livechat.css' %}" />
    </head>
    <body>
        <div id="wrapper">
            <div id="menu">
                <p class="welcome">Welcome, <b></b></p>
                <p class="logout"><a id="exit" href="#">Exit Chat</a></p>
            </div>

            <div id="chatbox"></div>

            <form name="message" action="">
                <input name="usermsg" type="text" id="usermsg" />
                <input name="submitmsg" type="submit" id="submitmsg" value="Send" />
            </form>
        </div>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script type="text/javascript">
            // jQuery Document
            $(document).ready(function () {});
        </script>
    </body>
</html>

templates/include/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Headers - 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/navbar/reset.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navbar/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navbar/header-1.css' %}" />
  </head>
  <body>
    <!-- Header Start -->
    <header class="site-header">
      <div class="wrapper site-header__wrapper">
        <a href="#" class="brand">Brand</a>
        <nav class="nav">
          <button class="nav__toggle" aria-expanded="false" type="button">
            menu
          </button>
          <ul class="nav__wrapper">
            <li class="nav__item"><a href="#">Home</a></li>
            <li class="nav__item"><a href="#">About</a></li>
            <li class="nav__item"><a href="#">Services</a></li>
            <li class="nav__item"><a href="#">Hire us</a></li>
            <li class="nav__item"><a href="#">Contact</a></li>
          </ul>
        </nav>
      </div>
    </header>
    <!-- Header End -->

    <script src="{% static 'js/navbar/header-1.js' %}"></script>
  </body>
</html>

templates/include/service.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}SERVICES{% endblock %}
{% block content %}
<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="{% static 'css/service/service.css' %}">
</head>

<body>
    <div class="article-clean">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
                    <div class="intro">
                        <h1 class="text-center">{{results.name}}</h1>
<!--                        <p class="text-center"><span class="by">by</span> <a href="#">Author Name</a><span class="date">Sept 8th, 2018 </span></p>-->
                        <img class="img-fluid" src="{{results.img.url}}">
                        </div>
                    <div class="text">
                        <p>{{results.desc}}</p>
<!--                        <p>Sed lobortis mi. Suspendisse vel placerat ligula. <span style="text-decoration: underline;">Vivamus</span> ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in-->
<!--                            justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>-->
<!--                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac lacus. <strong>Ut vehicula rhoncus</strong> elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit <em>pulvinar dict</em> vel in justo. Vestibulum-->
<!--                            ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>-->
<!--                        <h2>Aliquam In Arcu </h2>-->
<!--                        <p>Suspendisse vel placerat ligula. Vivamus ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices-->
<!--                            posuere cubilia Curae.</p>-->
<!--&lt;!&ndash;                        <figure><img class="figure-img" src="{{results.img.url}}">&ndash;&gt;-->
<!--&lt;!&ndash;                            <figcaption>Caption</figcaption>&ndash;&gt;-->
<!--&lt;!&ndash;                        </figure>&ndash;&gt;-->
<!--                        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Suspendisse vel placerat ligula. Vivamus ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit-->
<!--                            pulvinar dictum vel in justo.</p>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

</body>
{% endblock %}

<!--<div>-->
<!--        <div>-->
<!--            <p><a href="{% url 'essbeeapp:index' %}" >Home</a></p>-->
<!--        </div>-->
<!--        <div>-->
<!--            <br>-->

<!--            <div class="row"  >-->
<!--                <div class="col-md-4"   >-->
<!--                    <div class="thumbnail"   >-->
<!--                         <center>-->
<!--                    <img src="{{results.img.url}}" alt="{{results.name}}" class="img-rounded"   height="250px" width="250px" >-->
<!--                 </center>-->
<!--                    </div>-->
<!--            </div>-->
<!--    -->
<!--            </div>-->

<!--            <div>-->
<!--                <div>-->

<!--                    <h3>{{results.name}}</h3>-->

<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->